### ISSUE TITLE
No release of org.testcontainers:oracle-xe since TestContainers 1.2.1?

### ISSUE THREAD

**Issue by edgarvonk** [testcontainers/testcontainers-java-module-oracle-xe#2]
Hi,

If I am not mistaken there has not been a release of this module since TestContainers 1.2.1? At least I cannot find it in any of the Maven repos:
https://mvnrepository.com/artifact/org.testcontainers/oracle-xe

I tried using version 1.2.1 with Test Containers 1.4.2 but that fails because it is not compatible.

It is possible to always release this module together with Test Containers itself?

cheers

**Comment by kiview** [comment]
As a fallback, you can always resort to the [Jitpack](https://jitpack.io/#testcontainers/testcontainers-java-module-oracle-xe) repository.

I'll look into upgrading to 1.4.x.

**Comment by rnorth** [comment]
1.4.3 was released on 14th October, so I'll close this.
